### ISSUE TITLE
PCA?

### ISSUE THREAD

**Issue by street-grease-coder** [vancegroup/EigenArduino#3]
Is it just me or is PCA missing in this library? Is the idea to just use svd and perform further steps as needed (to get PCA)?

**Comment by rpavlik** [comment]
This is just a modification of (an old version of) the upstream Eigen lib. https://gitlab.com/libeigen/eigen

**Comment by street-grease-coder** [comment]
Could this be included by any chance?!

**Comment by rpavlik** [comment]
I haven't touched this library in over a decade, while upstream is actively developed. This is effectively just a small patch set on top. If Eigen doesn't offer PCA itself directly, there are probably libraries that build on it to do so, since it's basically the most common linear algebra library these days outside of gamedev (where glm is more common I think).

You're welcome to build a PCA library, if needed, on top of Eigen and publish that as open source, but I will not be doing so, sorry.
